#!/usr/bin/env sh

export HOOK_TYPE=`basename $0`

if [ "`git config hooks.verbose`" = "true" ]; then
  HOOK_VERBOSE=1
fi

if [ "`git config hooks.enabled`" = 'false' ]; then
  if [ $HOOK_VERBOSE ]; then
    echo "Skipping all hooks"
  fi
  exit 0
fi

if [ "`git config hooks.${HOOK_TYPE}.enabled`" != 'true' ]; then
  if [ $HOOK_VERBOSE ]; then
    echo "Skipping ${HOOK_TYPE}"
  fi
  exit 0
fi

RETVAL=0

if [ -d ${0}.d ]; then
  for i in ${0}.d/*; do
    export HOOK_NAME=`basename $i | sed "s/\./-/g"`

    if [ -x ${i} ]; then
      if [ "`git config hooks.${HOOK_TYPE}.${HOOK_NAME}`" != 'true' ]; then
        if [ $HOOK_VERBOSE ]; then
          echo "Skipping ${HOOK_TYPE} - ${HOOK_NAME}"
        fi
      else
        ${i} $@ || RETVAL=$?
      fi
    fi
  done
fi

exit $RETVAL
