#!/bin/sh

HOOK_NAME=`basename $0`

if [ "`git config hooks.${HOOK_NAME}.enabled`" != 'true' ]; then
  echo "Skipping ${HOOK_NAME}"
  exit 0
fi

if [ -d ${0}.d ]; then
  for i in ${0}.d/*; do
    SUBHOOK_NAME=`basename $i | sed "s/\./-/g"`
    if [ -x ${i} ]; then
      if [ "`git config hooks.${HOOK_NAME}.${SUBHOOK_NAME}`" != 'true' ]; then
        echo "Skipping ${HOOK_NAME} - ${SUBHOOK_NAME}"
      else
        ${i}
        RETVAL=$?
        [ $RETVAL -ne 0 ] && exit $RETVAL
      fi
    fi
  done
fi

exit 0
